[package]
name = "trezoa-serde-varint"
description = "Trezoa definitions for integers that serialize to variable size"
documentation = "https://docs.rs/trezoa-serde-varint"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
serde = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
rand = { workspace = true }
serde_derive = { workspace = true }
trezoa-short-vec = { workspace = true, features = ["serde"] }
