[package]
name = "trezoa-packet"
description = "The definition of a Trezoa network packet."
documentation = "https://docs.rs/trezoa-packet"
version = "4.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:bincode", "serde"]
dev-context-only-utils = ["bincode"]
serde = [
    "bitflags/serde",
    "dep:cfg_eval",
    "dep:serde",
    "dep:serde_derive",
    "dep:serde_with",
    "trezoa-pubkey/serde",
]
frozen-abi = ["dep:trezoa-frozen-abi", "dep:trezoa-frozen-abi-macro"]

[dependencies]
bincode = { workspace = true, optional = true }
bitflags = { workspace = true }
cfg_eval = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
serde_with = { workspace = true, optional = true, features = ["macros"] }
trezoa-frozen-abi = { workspace = true, optional = true, features = ["frozen-abi"] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = ["frozen-abi"] }
trezoa-pubkey = { workspace = true }

[dev-dependencies]
trezoa-packet = { path = ".", features = ["dev-context-only-utils"] }
trezoa-pubkey = { workspace = true, features = ["std"] }
static_assertions = { workspace = true }

[lints]
workspace = true
