[package]
name = "trezoa-sysvar"
description = "Trezoa sysvar account types"
documentation = "https://docs.rs/trezoa-sysvar"
version = "3.1.1"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:bincode", "serde"]
bytemuck = ["dep:bytemuck", "dep:bytemuck_derive"]
dev-context-only-utils = ["bincode", "bytemuck"]
frozen-abi = ["dep:trezoa-frozen-abi", "dep:trezoa-frozen-abi-macro"]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "trezoa-clock/serde",
    "trezoa-epoch-rewards/serde",
    "trezoa-epoch-schedule/serde",
    "trezoa-fee-calculator/serde",
    "trezoa-last-restart-slot/serde",
    "trezoa-rent/serde",
    "trezoa-slot-hashes/serde",
    "trezoa-slot-history/serde",
]

[dependencies]
bincode = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }
bytemuck_derive = { workspace = true, optional = true }
lazy_static = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
trezoa-account-info = { workspace = true }
trezoa-clock = { workspace = true, features = ["sysvar"] }
trezoa-epoch-rewards = { workspace = true, features = ["sysvar"] }
trezoa-epoch-schedule = { workspace = true, features = ["sysvar"] }
trezoa-fee-calculator = { workspace = true }
trezoa-frozen-abi = { workspace = true, optional = true }
trezoa-frozen-abi-macro = { workspace = true, optional = true }
trezoa-hash = { workspace = true, features = ["bytemuck"] }
trezoa-last-restart-slot = { workspace = true, features = ["sysvar"] }
trezoa-program-entrypoint = { workspace = true }
trezoa-program-error = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-rent = { workspace = true, features = ["sysvar"] }
trezoa-sdk-ids = { workspace = true }
trezoa-sdk-macro = { workspace = true }
trezoa-slot-hashes = { workspace = true, features = ["sysvar"] }
trezoa-slot-history = { workspace = true, features = ["sysvar"] }
trezoa-sysvar-id = { workspace = true }

[target.'cfg(not(target_os = "trezoa"))'.dependencies]
base64 = { workspace = true }
trezoa-instruction = { workspace = true, features = ["std"] }
trezoa-program-memory = { workspace = true }

[target.'cfg(target_os = "trezoa")'.dependencies]
trezoa-define-syscall = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
serial_test = { workspace = true }
trezoa-example-mocks = { path = "../example-mocks" }
trezoa-hash = { workspace = true, features = ["atomic", "bytemuck"] }
trezoa-msg = { workspace = true, features = ["std"] }
trezoa-sha256-hasher = { workspace = true }
trezoa-sysvar = { path = ".", features = ["dev-context-only-utils"] }
test-case = { workspace = true }

[lints]
workspace = true
