[package]
name = "trezoa-stable-layout"
description = "Trezoa types with stable memory layouts. Internal use only."
documentation = "https://docs.rs/trezoa-stable-layout"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[dependencies]
trezoa-instruction = { workspace = true, default-features = false, features = [
    "std",
] }
trezoa-pubkey = { workspace = true, default-features = false }

[dev-dependencies]
memoffset = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["std"], default-features = false }
