[package]
name = "trezoa-serialize-utils"
description = "Trezoa helpers for reading and writing bytes."
documentation = "https://docs.rs/trezoa-serialize-utils"
version = "3.1.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trezoa-instruction-error = { workspace = true }
trezoa-pubkey = { workspace = true, default-features = false }
trezoa-sanitize = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
borsh = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
trezoa-pubkey = { workspace = true, default-features = false, features = [
    "borsh",
    "serde",
] }
