[package]
name = "trezoa-program-memory"
description = "Basic low-level memory operations for Trezoa."
documentation = "https://docs.rs/trezoa-program-memory"
version = "3.1.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[target.'cfg(any(target_os = "trezoa", target_arch = "bpf"))'.dependencies]
trezoa-define-syscall = { workspace = true }

[lints]
workspace = true
