[package]
name = "trezoa-presigner"
description = "A Trezoa `Signer` implementation representing an externally-constructed `Signature`."
documentation = "https://docs.rs/trezoa-presigner"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trezoa-pubkey = { workspace = true }
trezoa-signature = { workspace = true, features = ["verify"] }
trezoa-signer = { workspace = true }

[dev-dependencies]
trezoa-keypair = { workspace = true }
