[package]
name = "trezoa-nonce-account"
description = "Trezoa nonce account utils."
documentation = "https://docs.rs/trezoa-nonce-account"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trezoa-account = { workspace = true, features = ["bincode"] }
trezoa-hash = { workspace = true }
trezoa-nonce = { workspace = true, features = ["serde"] }
trezoa-sdk-ids = { workspace = true }

[dev-dependencies]
trezoa-fee-calculator = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["std"] }
