[package]
name = "trezoa-pubkey"
description = "Trezoa account addresses"
documentation = "https://docs.rs/trezoa-pubkey"
version = "4.0.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
borsh = ["trezoa-address/borsh"]
bytemuck = ["trezoa-address/bytemuck"]
curve25519 = ["trezoa-address/curve25519"]
default = ["std"]
dev-context-only-utils = ["trezoa-address/dev-context-only-utils"]
frozen-abi = ["trezoa-address/frozen-abi"]
rand = ["dep:rand", "trezoa-address/rand"]
serde = ["trezoa-address/serde"]
sha2 = ["trezoa-address/sha2"]
std = ["trezoa-address/atomic", "trezoa-address/std"]
alloc = ["trezoa-address/alloc"]

[dependencies]
rand = { workspace = true, optional = true }
trezoa-address = { workspace = true, features = [
    "copy",
    "decode",
    "error",
    "sanitize",
    "syscalls",
] }

[lints]
workspace = true
