[package]
name = "trezoa-loader-v2-interface"
description = "Trezoa non-upgradable BPF loader v2 instructions."
documentation = "https://docs.rs/trezoa-loader-v2-interface"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:trezoa-instruction", "serde"]
serde = ["dep:serde", "dep:serde_bytes", "dep:serde_derive"]

[dependencies]
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
trezoa-instruction = { workspace = true, features = ["bincode", "std"], optional = true }
trezoa-pubkey = { workspace = true }
trezoa-sdk-ids = { workspace = true }

[lints]
workspace = true
