[package]
name = "trezoa-vote-interface"
description = "Trezoa vote interface."
documentation = "https://docs.rs/trezoa-vote-interface"
version = "5.0.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = [
    "dep:bincode",
    "dep:trezoa-serialize-utils",
    "dep:trezoa-system-interface",
    "serde",
]
dev-context-only-utils = [
    "bincode",
    "dep:arbitrary",
    "trezoa-pubkey/dev-context-only-utils",
]
frozen-abi = [
    "dep:trezoa-frozen-abi",
    "dep:trezoa-frozen-abi-macro",
    "serde",
    "trezoa-hash/frozen-abi",
    "trezoa-pubkey/frozen-abi",
    "trezoa-short-vec/frozen-abi",
]
serde = [
    "dep:cfg_eval",
    "dep:serde",
    "dep:serde_derive",
    "dep:serde_with",
    "dep:trezoa-serde-varint",
    "dep:trezoa-short-vec",
    "serde/alloc",
    "trezoa-hash/serde",
    "trezoa-pubkey/serde",
    "trezoa-short-vec/serde",
]

[dependencies]
arbitrary = { workspace = true, features = ["derive"], optional = true }
bincode = { workspace = true, optional = true }
cfg_eval = { workspace = true, optional = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
serde_with = { workspace = true, features = ["macros"], optional = true }
trezoa-clock = { workspace = true }
trezoa-frozen-abi = { workspace = true, features = ["frozen-abi"], optional = true }
trezoa-frozen-abi-macro = { workspace = true, features = ["frozen-abi"], optional = true }
trezoa-hash = { workspace = true, features = ["decode"] }
trezoa-instruction = { workspace = true, features = ["std"] }
trezoa-instruction-error = { workspace = true, features = ["num-traits"] }
trezoa-pubkey = { workspace = true }
trezoa-rent = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-serde-varint = { workspace = true, optional = true }
trezoa-serialize-utils = { workspace = true, optional = true }
trezoa-short-vec = { workspace = true, optional = true }
trezoa-system-interface = { workspace = true, features = ["bincode"], optional = true }

[target.'cfg(target_os = "trezoa")'.dependencies]
trezoa-serialize-utils = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
rand = { workspace = true }
trezoa-epoch-schedule = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-vote-interface = { path = ".", features = ["dev-context-only-utils"] }

[lints]
workspace = true
