[package]
name = "trezoa-instruction"
description = "Types for directing the execution of Trezoa programs."
documentation = "https://docs.rs/trezoa-instruction"
version = "3.1.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:bincode", "dep:serde"]
borsh = ["dep:borsh"]
default = ["std"]
frozen-abi = ["dep:trezoa-frozen-abi", "dep:trezoa-frozen-abi-macro", "serde", "std"]
serde = ["dep:serde", "dep:serde_derive", "trezoa-pubkey/serde"]
std = ["serde?/std", "borsh?/std"]
syscalls = ["std"]

[dependencies]
bincode = { workspace = true, optional = true }
borsh = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
trezoa-frozen-abi = { workspace = true, optional = true }
trezoa-frozen-abi-macro = { workspace = true, optional = true }
trezoa-instruction-error = { workspace = true, features = ["num-traits"] }
trezoa-pubkey = { workspace = true, default-features = false }

[target.'cfg(target_os = "trezoa")'.dependencies]
trezoa-define-syscall = { workspace = true }

[dev-dependencies]
trezoa-instruction = { path = ".", features = ["borsh"] }
trezoa-pubkey = { workspace = true, features = ["std"] }

[lints]
workspace = true
