[package]
name = "trezoa-shred-version"
description = "Calculation of shred versions."
documentation = "https://docs.rs/trezoa-shred-version"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trezoa-hard-forks = { workspace = true }
trezoa-hash = { workspace = true }
trezoa-sha256-hasher = { workspace = true }

[dev-dependencies]
trezoa-sha256-hasher = { workspace = true, features = ["sha2"] }

[lints]
workspace = true
