[package]
name = "trezoa-program-entrypoint"
description = "The Trezoa BPF program entrypoint supported by the latest BPF loader."
documentation = "https://docs.rs/trezoa-program-entrypoint"
version = "3.1.1"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

rust-version = "1.81.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trezoa-account-info = { workspace = true }
trezoa-define-syscall = { workspace = true }
trezoa-program-error = { workspace = true }
trezoa-pubkey = { workspace = true, default-features = false }

[dev-dependencies]
trezoa-msg = { workspace = true, features = ["std"] }
