[package]
name = "trezoa-nonce"
description = "Trezoa durable transaction nonces."
documentation = "https://docs.rs/trezoa-nonce"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
dev-context-only-utils = ["serde"]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "serde/alloc",
    "trezoa-fee-calculator/serde",
    "trezoa-hash/serde",
    "trezoa-pubkey/serde",
]

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
trezoa-fee-calculator = { workspace = true }
trezoa-hash = { workspace = true, features = ["copy", "decode"] }
trezoa-pubkey = { workspace = true, default-features = false }
trezoa-sha256-hasher = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }
trezoa-nonce = { path = ".", features = ["dev-context-only-utils"] }
trezoa-pubkey = { workspace = true, features = ["std"], default-features = false }
