[package]
name = "trezoa-program-log"
description = "Lightweight log utility for Trezoa programs"
version = "1.1.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
readme = "./README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lib]
crate-type = ["rlib"]

[features]
default = ["macro"]
macro = ["dep:trezoa-program-log-macro"]
std = []

[dependencies]
trezoa-program-log-macro = { workspace = true, optional = true }

[target.'cfg(any(target_os = "trezoa", target_arch = "bpf"))'.dependencies]
trezoa-define-syscall = { workspace = true }

[lints]
workspace = true
