[package]
name = "trezoa-quic-definitions"
description = "Definitions related to Trezoa over QUIC."
documentation = "https://docs.rs/trezoa-quic-definitions"
version = "3.0.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trezoa-keypair = { workspace = true }

[lints]
workspace = true
