[package]
name = "trezoa-message"
description = "Trezoa transaction message types."
documentation = "https://docs.rs/trezoa-message"
version = "3.0.1"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:bincode", "serde"]
blake3 = ["dep:blake3"]
dev-context-only-utils = ["bincode", "blake3"]
frozen-abi = [
    "dep:trezoa-frozen-abi",
    "dep:trezoa-frozen-abi-macro",
    "trezoa-address/frozen-abi",
    "trezoa-hash/frozen-abi",
    "serde",
    "trezoa-short-vec/frozen-abi",
]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "dep:trezoa-short-vec",
    "serde/alloc",
    "trezoa-address/serde",
    "trezoa-hash/serde",
    "trezoa-short-vec/serde",
]
wincode = ["dep:wincode", "trezoa-hash/wincode", "trezoa-address/wincode"]

[dependencies]
bincode = { workspace = true, optional = true }
blake3 = { workspace = true, features = ["traits-preview"], optional = true }
lazy_static = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
trezoa-address = { workspace = true }
trezoa-frozen-abi = { workspace = true, optional = true }
trezoa-frozen-abi-macro = { workspace = true, optional = true }
trezoa-hash = { workspace = true, features = ["decode", "sanitize"] }
trezoa-instruction = { workspace = true, features = ["std"] }
trezoa-sanitize = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-short-vec = { workspace = true, optional = true }
trezoa-transaction-error = { workspace = true }
wincode = { workspace = true, optional = true, features = [
    "std",
    "trezoa-short-vec",
] }

[dev-dependencies]
anyhow = { workspace = true }
bitflags = { workspace = true }
borsh = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
trezoa-address-lookup-table-interface = { workspace = true, features = [
    "bincode",
    "bytemuck",
] }
trezoa-example-mocks = { path = "../example-mocks" }
trezoa-hash = { workspace = true, features = ["atomic"] }
trezoa-instruction = { workspace = true, features = ["borsh"] }
trezoa-instruction-error = { workspace = true }
trezoa-message = { path = ".", features = ["dev-context-only-utils"] }
trezoa-nonce = { workspace = true }
trezoa-system-interface = { workspace = true, features = ["bincode"] }
static_assertions = { workspace = true }

[lints]
workspace = true
