[package]
name = "trezoa-system-interface"
version = "3.0.0"
description = "Instructions and constructors for the System program"
readme = "README.md"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = "1.81.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lib]
crate-type = ["rlib"]

[features]
alloc = []
bincode = ["dep:trezoa-instruction", "alloc", "serde"]
frozen-abi = [
    "dep:trezoa-frozen-abi",
    "dep:trezoa-frozen-abi-macro",
    "serde",
    "std",
    "trezoa-address/frozen-abi",
    "trezoa-address/std",
]
serde = ["dep:serde", "dep:serde_derive", "serde/alloc", "trezoa-address/serde"]
std = []

[dependencies]
num-traits = { workspace = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
trezoa-address = { workspace = true, features = ["decode"] }
trezoa-frozen-abi = { workspace = true, features = ["frozen-abi"], optional = true }
trezoa-frozen-abi-macro = { workspace = true, features = ["frozen-abi"], optional = true }
trezoa-instruction = { workspace = true, features = ["bincode", "std"], optional = true }
trezoa-msg = { workspace = true }
trezoa-program-error = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
borsh = { workspace = true, features = ["derive", "unstable__schema"] }
trezoa-account-info = { workspace = true }
trezoa-cpi = { path = "../cpi" }
trezoa-example-mocks = { path = "../example-mocks" }
trezoa-nonce = { workspace = true }
trezoa-program-entrypoint = { workspace = true }
trezoa-program-error = { workspace = true, features = ["borsh"] }
trezoa-system-interface = { path = ".", features = ["bincode"] }
trezoa-sysvar = { workspace = true }
trezoa-sysvar-id = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
