[package]
name = "trezoa-sdk-wasm-js"
description = "Trezoa SDK Wasm JS"
documentation = "https://docs.rs/trezoa-sdk-wasm-js"
version = "1.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["wasm32-unknown-unknown"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bincode = { workspace = true }
trezoa-address = { workspace = true, features = ["curve25519", "sha2", "std"] }
trezoa-hash = { workspace = true }
trezoa-instruction = { workspace = true, features = ["std"] }
trezoa-keypair = { workspace = true }
trezoa-message = { workspace = true }
trezoa-packet = { workspace = true }
trezoa-signature = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-transaction = { workspace = true, features = ["bincode", "verify"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
getrandom = { workspace = true, features = ["wasm_js"] }
js-sys = { workspace = true }
log = { workspace = true }
wasm-bindgen = { workspace = true }

[lints]
workspace = true
