[package]
name = "trezoa-short-vec"
description = "Trezoa compact serde-encoding of vectors with small length."
documentation = "https://docs.rs/trezoa-short-vec"
version = "3.1.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = ["serde"]
serde = ["dep:serde_core"]
frozen-abi = ["dep:trezoa-frozen-abi", "dep:trezoa-frozen-abi-macro"]

[dependencies]
serde_core = { workspace = true, optional = true }
trezoa-frozen-abi = { workspace = true, optional = true, features = [
    "frozen-abi",
] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = [
    "frozen-abi",
] }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
serde_json = { workspace = true }
trezoa-short-vec = { path = ".", features = ["serde"] }

[lints]
workspace = true
