[package]
name = "trezoa-secp256k1-program"
description = "Instructions for the Trezoa Secp256k1 native program."
documentation = "https://docs.rs/trezoa-secp256k1-program"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = [
    "dep:bincode",
    "dep:trezoa-instruction",
    "dep:trezoa-sdk-ids",
    "serde",
]
dev-context-only-utils = ["bincode"]
serde = ["dep:serde", "dep:serde_derive"]

[dependencies]
bincode = { workspace = true, optional = true }
digest = { workspace = true }
k256 = { workspace = true, features = ["ecdsa-core"] }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
sha3 = { workspace = true }
trezoa-instruction = { workspace = true, features = ["std"], optional = true }
trezoa-sdk-ids = { workspace = true, optional = true }
trezoa-signature = { workspace = true, features = ["std"] }

[dev-dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
rand = "0.8" # k256 still uses rand_core v0.6
trezoa-account-info = { workspace = true }
trezoa-example-mocks = { path = "../example-mocks" }
trezoa-instruction = { workspace = true }
trezoa-instructions-sysvar = { workspace = true }
trezoa-keccak-hasher = { workspace = true, features = ["sha3"] }
trezoa-msg = { workspace = true, features = ["std"] }
trezoa-program-error = { workspace = true }
trezoa-secp256k1-program = { path = ".", features = ["bincode"] }
