[package]
name = "trezoa-slot-hashes"
description = "Types and utilities for the Trezoa SlotHashes sysvar."
documentation = "https://docs.rs/trezoa-slot-hashes"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
serde = ["dep:serde", "dep:serde_derive", "serde/alloc", "trezoa-hash/serde"]
sysvar = ["dep:trezoa-sdk-ids", "dep:trezoa-sysvar-id"]

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
trezoa-hash = { workspace = true, features = ["decode"] }
trezoa-sdk-ids = { workspace = true, optional = true }
trezoa-sysvar-id = { workspace = true, optional = true }

[dev-dependencies]
trezoa-sha256-hasher = { workspace = true }
