[package]
name = "trezoa-transaction"
description = "Trezoa transaction-types"
documentation = "https://docs.rs/trezoa-transaction"
version = "3.0.2"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = [
    "dep:bincode",
    "dep:trezoa-signer",
    "serde",
    "trezoa-message/bincode",
]
blake3 = ["bincode", "trezoa-message/blake3"]
dev-context-only-utils = ["blake3", "serde", "verify", "trezoa-hash/atomic"]
frozen-abi = [
    "dep:trezoa-frozen-abi",
    "dep:trezoa-frozen-abi-macro",
    "trezoa-transaction-error/frozen-abi",
    "trezoa-signature/frozen-abi",
    "trezoa-message/frozen-abi",
]
serde = [
    "dep:serde",
    "dep:serde_derive",
    "dep:trezoa-short-vec",
    "trezoa-message/serde",
    "trezoa-signature/serde",
    "trezoa-transaction-error/serde",
    "trezoa-short-vec/serde",
]
verify = ["blake3", "trezoa-signature/verify"]
wincode = ["dep:wincode", "trezoa-message/wincode", "trezoa-signature/wincode"]

[dependencies]
bincode = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
trezoa-address = { workspace = true }
trezoa-frozen-abi = { workspace = true, optional = true, features = ["frozen-abi"] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = ["frozen-abi"] }
trezoa-hash = { workspace = true }
trezoa-instruction = { workspace = true }
trezoa-instruction-error = { workspace = true }
trezoa-message = { workspace = true }
trezoa-sanitize = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-short-vec = { workspace = true, optional = true }
trezoa-signature = { workspace = true }
trezoa-signer = { workspace = true, optional = true }
trezoa-transaction-error = { workspace = true }
wincode = { workspace = true, optional = true, features = [
    "trezoa-short-vec",
    "alloc",
] }

[dev-dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
borsh = { workspace = true }
proptest = { workspace = true }
trezoa-example-mocks = { path = "../example-mocks" }
trezoa-hash = { workspace = true, features = ["atomic"] }
trezoa-instruction = { workspace = true, features = ["borsh"] }
trezoa-keypair = { workspace = true }
trezoa-nonce = { workspace = true }
trezoa-packet = { workspace = true }
trezoa-presigner = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["rand"] }
trezoa-sha256-hasher = { workspace = true }
trezoa-system-interface = { workspace = true, features = ["bincode"] }
trezoa-transaction = { path = ".", features = [
    "dev-context-only-utils",
    "wincode",
] }
trezoa-vote-interface = { workspace = true, features = ["bincode"] }
static_assertions = { workspace = true }
