[package]
name = "trezoa-keypair"
description = "Concrete implementation of a Trezoa `Signer`."
documentation = "https://docs.rs/trezoa-keypair"
version = "3.1.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
seed-derivable = [
    "dep:trezoa-derivation-path",
    "dep:trezoa-seed-derivable",
    "dep:ed25519-dalek-bip32",
]

[dependencies]
ed25519-dalek = { workspace = true, features = ["rand_core"] }
ed25519-dalek-bip32 = { workspace = true, optional = true }
five8 = { workspace = true }
rand = { workspace = true }
trezoa-address = { workspace = true, features = ["decode"] }
trezoa-derivation-path = { workspace = true, optional = true }
trezoa-seed-derivable = { workspace = true, optional = true }
trezoa-seed-phrase = { workspace = true }
trezoa-signature = { workspace = true, features = ["std", "verify"] }
trezoa-signer = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
static_assertions = { workspace = true }
tiny-bip39 = { workspace = true }
