[package]
name = "trezoa-program"
description = "Trezoa Program"
documentation = "https://docs.rs/trezoa-program"
readme = "README.md"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
rust-version = "1.81.0"                          # trezoa platform-tools rust version
include = ["src/**/*", "README.md"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lib]
crate-type = ["rlib"]

[features]
default = ["borsh"]
borsh = [
    "dep:trezoa-borsh",
    "trezoa-hash/borsh",
    "trezoa-instruction/borsh",
    "trezoa-program-error/borsh",
    "trezoa-pubkey/borsh",
]
dev-context-only-utils = [
    "trezoa-instructions-sysvar/dev-context-only-utils",
    "dep:trezoa-system-interface",
    "trezoa-system-interface/bincode",
]
frozen-abi = [
    "dep:trezoa-frozen-abi",
    "dep:trezoa-frozen-abi-macro",
    "trezoa-epoch-rewards/frozen-abi",
    "trezoa-epoch-schedule/frozen-abi",
    "trezoa-fee-calculator/frozen-abi",
    "trezoa-hash/frozen-abi",
    "trezoa-instruction/frozen-abi",
    "trezoa-pubkey/frozen-abi",
    "trezoa-rent/frozen-abi",
    "trezoa-short-vec/frozen-abi",
    "trezoa-sysvar/frozen-abi",
]

[dependencies]
memoffset = { workspace = true }
trezoa-account-info = { workspace = true, features = ["bincode"] }
trezoa-big-mod-exp = { workspace = true }
trezoa-blake3-hasher = { workspace = true, features = ["blake3"] }
trezoa-borsh = { workspace = true, optional = true }
trezoa-clock = { workspace = true, features = ["serde", "sysvar"] }
trezoa-cpi = { workspace = true }
trezoa-epoch-rewards = { workspace = true, features = ["serde", "sysvar"] }
trezoa-epoch-schedule = { workspace = true, features = ["serde", "sysvar"] }
trezoa-epoch-stake = { workspace = true }
trezoa-fee-calculator = { workspace = true, features = ["serde"] }
trezoa-frozen-abi = { workspace = true, optional = true, features = ["frozen-abi"] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = ["frozen-abi"] }
trezoa-hash = { workspace = true, features = [
    "bytemuck",
    "serde",
    "std",
] }
trezoa-instruction = { workspace = true, default-features = false, features = [
    "bincode",
    "serde",
    "std",
    "syscalls",
] }
trezoa-instruction-error = { workspace = true, features = ["num-traits"] }
trezoa-instructions-sysvar = { workspace = true }
trezoa-keccak-hasher = { workspace = true, features = ["sha3"] }
trezoa-last-restart-slot = { workspace = true, features = ["serde", "sysvar"] }
trezoa-msg = { workspace = true, features = ["std"] }
trezoa-native-token = { workspace = true }
trezoa-program-entrypoint = { workspace = true }
trezoa-program-error = { workspace = true, features = ["serde"] }
trezoa-program-memory = { workspace = true }
trezoa-program-option = { workspace = true }
trezoa-program-pack = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["bytemuck", "curve25519", "serde", "std"] }
trezoa-rent = { workspace = true, features = ["serde", "sysvar"] }
trezoa-sdk-ids = { workspace = true }
trezoa-secp256k1-recover = { workspace = true }
trezoa-serde-varint = { workspace = true }
trezoa-serialize-utils = { workspace = true }
trezoa-sha256-hasher = { workspace = true, features = ["sha2"] }
trezoa-short-vec = { workspace = true }
trezoa-slot-hashes = { workspace = true, features = ["serde", "sysvar"] }
trezoa-slot-history = { workspace = true, features = ["serde", "sysvar"] }
trezoa-stable-layout = { workspace = true }
trezoa-system-interface = { optional = true, workspace = true, features = ["bincode"] }
trezoa-sysvar = { workspace = true, features = ["bincode", "bytemuck"] }
trezoa-sysvar-id = { workspace = true }

[target.'cfg(not(target_os = "trezoa"))'.dependencies]
trezoa-example-mocks = { workspace = true }

[target.'cfg(target_os = "trezoa")'.dependencies]
trezoa-define-syscall = { workspace = true }

[dev-dependencies]
trezoa-pubkey = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-sysvar = { workspace = true, features = ["dev-context-only-utils"] }

[lints]
workspace = true
