[package]
name = "trezoa-sdk"
description = "Trezoa SDK"
documentation = "https://docs.rs/trezoa-sdk"
readme = "README.md"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
include = ["src/**/*", "README.md"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lib]
crate-type = ["rlib"]

[features]
default = [
    "borsh",
    "full",  # functionality that is not compatible or needed for on-chain programs
]
full = [
    "trezoa-signature",
    "trezoa-pubkey/rand",
    "dep:trezoa-keypair",
    "dep:trezoa-offchain-message",
    "dep:trezoa-presigner",
    "dep:trezoa-seed-derivable",
    "dep:trezoa-seed-phrase",
    "dep:trezoa-shred-version",
    "dep:trezoa-signer",
    "dep:trezoa-transaction",
    "dep:trezoa-transaction-error",
]
borsh = ["trezoa-program/borsh"]
dev-context-only-utils = [
    "trezoa-account/dev-context-only-utils",
    "trezoa-program/dev-context-only-utils",
    "trezoa-transaction/dev-context-only-utils",
]
frozen-abi = [
    "trezoa-fee-structure/frozen-abi",
    "trezoa-account/frozen-abi",
    "trezoa-inflation/frozen-abi",
    "trezoa-program/frozen-abi",
    "trezoa-short-vec/frozen-abi",
    "trezoa-signature/frozen-abi",
    "trezoa-transaction/frozen-abi",
    "trezoa-transaction-error/frozen-abi",
]

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true }
trezoa-account = { workspace = true, features = ["bincode"] }
trezoa-epoch-info = { workspace = true, features = ["serde"] }
trezoa-epoch-rewards-hasher = { workspace = true }
trezoa-fee-structure = { workspace = true, features = ["serde"] }
trezoa-inflation = { workspace = true, features = ["serde"] }
trezoa-keypair = { workspace = true, optional = true, features = [
    "seed-derivable",
] }
trezoa-message = { workspace = true, features = ["serde"] }
trezoa-offchain-message = { workspace = true, optional = true, features = ["verify"] }
trezoa-presigner = { workspace = true, optional = true }
trezoa-program = { workspace = true }
trezoa-program-memory = { workspace = true }
trezoa-pubkey = { workspace = true, default-features = false, features = [
    "std",
] }
trezoa-sanitize = { workspace = true }
trezoa-sdk-ids = { workspace = true }
trezoa-sdk-macro = { workspace = true }
trezoa-seed-derivable = { workspace = true, optional = true }
trezoa-seed-phrase = { workspace = true, optional = true }
trezoa-serde = { workspace = true }
trezoa-serde-varint = { workspace = true }
trezoa-short-vec = { workspace = true }
trezoa-shred-version = { workspace = true, optional = true }
trezoa-signature = { workspace = true, features = [
    "rand",
    "serde",
    "std",
    "verify",
], optional = true }
trezoa-signer = { workspace = true, optional = true }
trezoa-time-utils = { workspace = true }
trezoa-transaction = { workspace = true, features = [
    "blake3",
    "serde",
    "verify"
], optional = true }
trezoa-transaction-error = { workspace = true, features = [
    "serde",
], optional = true }
thiserror = { workspace = true }

[dev-dependencies]
trezoa-instructions-sysvar = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-program = { workspace = true, features = ["dev-context-only-utils"] }
trezoa-sdk = { path = ".", features = ["dev-context-only-utils"] }

[lints]
workspace = true
