[package]
name = "trezoa-instruction-view"
description = "Lightweight instruction representation"
documentation = "https://docs.rs/trezoa-instruction-view"
version = "1.0.0"
rust-version = "1.82.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
cpi = ["dep:trezoa-define-syscall", "dep:trezoa-program-error"]
slice-cpi = ["cpi"]

[dependencies]
trezoa-account-view = { workspace = true }
trezoa-address = { workspace = true }
trezoa-program-error = { workspace = true, optional = true }

[target.'cfg(any(target_os = "trezoa", target_arch = "bpf"))'.dependencies]
trezoa-define-syscall = { workspace = true, optional = true }

[lints]
workspace = true
