[package]
name = "trezoa-system-transaction"
description = "Functionality for creating system transactions."
documentation = "https://docs.rs/trezoa-system-transaction"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trezoa-hash = { workspace = true }
trezoa-keypair = { workspace = true }
trezoa-message = { workspace = true }
trezoa-pubkey = { workspace = true }
trezoa-signer = { workspace = true }
trezoa-system-interface = { workspace = true, features = ["bincode"] }
trezoa-transaction = { workspace = true, features = ["bincode"] }
