[package]
name = "trezoa-signature"
description = "Trezoa 64-byte signature type"
documentation = "https://docs.rs/trezoa-signature"
version = "3.1.0"
rust-version = "1.81.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
default = ["std", "alloc"]
alloc = ["wincode?/alloc"]
bytemuck = ["dep:bytemuck", "dep:bytemuck_derive"]
frozen-abi = ["dep:trezoa-frozen-abi", "dep:trezoa-frozen-abi-macro", "std"]
rand = ["dep:rand"]
serde = ["dep:serde", "dep:serde_derive", "dep:serde-big-array"]
std = ["alloc", "serde?/std", "wincode?/std"]
verify = ["dep:ed25519-dalek"]
wincode = ["dep:wincode"]

[dependencies]
bytemuck = { workspace = true, optional = true }
bytemuck_derive = { workspace = true, optional = true }
ed25519-dalek = { workspace = true, optional = true }
five8 = { workspace = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde-big-array = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
trezoa-frozen-abi = { workspace = true, optional = true, features = ["frozen-abi"] }
trezoa-frozen-abi-macro = { workspace = true, optional = true, features = ["frozen-abi"] }
trezoa-sanitize = { workspace = true }
wincode = { workspace = true, optional = true }

[dev-dependencies]
bincode = { workspace = true }
bs58 = { workspace = true, features = ["std"] }
curve25519-dalek = { workspace = true }
ed25519-dalek = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["std"] }
trezoa-short-vec = { workspace = true, features = ["serde"] }
trezoa-signature = { path = ".", features = ["serde"] }

[lints]
workspace = true
