[package]
name = "trezoa-package-metadata"
description = "Trezoa Package Metadata"
documentation = "https://docs.rs/trezoa-package-metadata"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
trezoa-package-metadata-macro = { workspace = true }
trezoa-pubkey = { workspace = true, features = ["std"] }
